language:
  - cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
before_script:
  - travis_retry wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C ~/.local
  - cd ~ && git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install catch2
script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - cmake --build .
  - ./BPlusTreeTest -d yes -r tap
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE

